# Generated by Django 5.2.5 on 2025-08-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_group_announcement_expense_lesson_homeworkgrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_video_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='lesson_materials'),
        ),
    ]
