# Generated by Django 5.2.5 on 2025-08-15 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_lesson_lesson_video_url_lesson_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_date_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(blank=True, default='16:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
