# Generated by Django 5.2.5 on 2025-08-15 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_usergroups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='teachergroups',
            options={'verbose_name': 'Teacher Group', 'verbose_name_plural': 'Teacher Groups'},
        ),
        migrations.AlterModelOptions(
            name='usergroups',
            options={'verbose_name': 'User Group', 'verbose_name_plural': 'User Groups'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(default='Matematika'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'schedule')},
        ),
        migrations.AlterUniqueTogether(
            name='teachergroups',
            unique_together={('teacher', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='usergroups',
            unique_together={('user', 'group')},
        ),
    ]
