# Generated by Django 5.2.5 on 2025-08-30 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_attendance_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homeworkgrade',
            unique_together={('lesson', 'student')},
        ),
        migrations.AlterField(
            model_name='activitygrade',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_activity_grades', to='common.lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitygrade',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='activitygrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_activity_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attendances', to='common.lesson'),
        ),
        migrations.AlterField(
            model_name='homeworkgrade',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='activitygrade',
            unique_together={('lesson', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('group', 'lesson_date', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='homeworkgrade',
            name='grade_type',
        ),
    ]
