# Generated by Django 5.2.5 on 2025-08-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_homeworkgrade_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='material',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ClassMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.FileField(blank=True, null=True, upload_to='students/lesson_materials/class_materials')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_materials', to='common.lesson')),
            ],
            options={
                'verbose_name': 'Class Material',
                'verbose_name_plural': 'Class Materials',
            },
        ),
        migrations.CreateModel(
            name='HomeworkMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.FileField(blank=True, null=True, upload_to='students/lesson_materials/homework_materials')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_materials', to='common.lesson')),
            ],
            options={
                'verbose_name': 'Homework Material',
                'verbose_name_plural': 'Homework Materials',
            },
        ),
    ]
