# Generated by Django 5.2.5 on 2025-09-05 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_group_course_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroups',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='common.group'),
        ),
    ]
