# Generated by Django 5.2.5 on 2025-09-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_teachergroups_date_joined_usergroups_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_name',
        ),
        migrations.AddField(
            model_name='group',
            name='lesson_name',
            field=models.CharField(default='Matematika'),
        ),
    ]
