# Generated by Django 5.2.5 on 2025-08-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
        ('users', '0002_remove_notification_is_read_and_more'),
    ]

    operations = [
    ]
