# Generated by Django 5.2.5 on 2025-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20250815_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
